// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SayaGym.Data;

#nullable disable

namespace SayaGym.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240530010709_AddOtherKey2EjercicioRutina")]
    partial class AddOtherKey2EjercicioRutina
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SayaGym.Models.AreasATrabajarUsuario", b =>
                {
                    b.Property<string>("AreaATrabajar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("AreaATrabajar", "IdUsuario");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("AreasATrabajarUsuario");
                });

            modelBuilder.Entity("SayaGym.Models.Ejercicio", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEjercicio"));

                    b.Property<string>("AreaATrabajar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdEjercicio");

                    b.ToTable("Ejercicios");

                    b.HasData(
                        new
                        {
                            IdEjercicio = 1,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar mancuernas hacia los lados del cuerpo hasta la altura de los hombros, manteniendo los brazos ligeramente flexionados.",
                            Nombre = "Elevación Lateral con Mancuernas"
                        },
                        new
                        {
                            IdEjercicio = 2,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar mancuernas hacia los lados del cuerpo, pero con los brazos ligeramente flexionados hacia adelante, trabajando la parte posterior de los hombros.",
                            Nombre = "Vuelo Posterior del Deltoides con Mancuernas"
                        },
                        new
                        {
                            IdEjercicio = 3,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar una mancuerna desde el muslo hasta la altura de los hombros, manteniendo los brazos extendidos hacia adelante.",
                            Nombre = "Elevación Frontal con Mancuerna"
                        },
                        new
                        {
                            IdEjercicio = 4,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Realizar estiramientos hacia adelante con una cuerda de cable, manteniendo los brazos extendidos y controlando el movimiento.",
                            Nombre = "Estiramientos de Rostro con Cuerda de Cable"
                        },
                        new
                        {
                            IdEjercicio = 5,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Sentarse y levantar mancuernas desde los hombros hacia arriba, extendiendo los brazos.",
                            Nombre = "Press de Hombros Sentado con Mancuernas"
                        },
                        new
                        {
                            IdEjercicio = 6,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar una barra con peso desde los muslos hasta los hombros, flexionando los codos.",
                            Nombre = "Curl de Barra"
                        },
                        new
                        {
                            IdEjercicio = 7,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar una mancuerna desde el muslo hasta el hombro, flexionando el codo",
                            Nombre = "Curl con Mancuerna"
                        },
                        new
                        {
                            IdEjercicio = 8,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar mancuernas con las palmas enfrentadas desde los muslos hasta los hombros, flexionando los codos",
                            Nombre = "Curl de Martillo con Mancuernas"
                        },
                        new
                        {
                            IdEjercicio = 9,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Realizar curls con una pesa kettlebell apoyando los brazos en un banco inclinado",
                            Nombre = "Curl de Predicador con Kettlebell"
                        },
                        new
                        {
                            IdEjercicio = 10,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar una polea con peso desde abajo hacia el hombro, con la palma hacia abajo.",
                            Nombre = "Curl Inverso con Cable a un Brazo"
                        },
                        new
                        {
                            IdEjercicio = 11,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Levantar una polea con peso desde abajo hacia el hombro, con las palmas enfrentadas",
                            Nombre = "Curl de Martillo con Cable a un Brazo"
                        },
                        new
                        {
                            IdEjercicio = 12,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Realizar curls con una banda elástica, flexionando los codos y resistiendo la tensión de la banda.",
                            Nombre = "Curl con Banda"
                        },
                        new
                        {
                            IdEjercicio = 13,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Sentarse en un banco inclinado y levantar una mancuerna desde el muslo hasta el hombro, flexionando el codo.",
                            Nombre = "Curl de Concentración con Mancuerna"
                        },
                        new
                        {
                            IdEjercicio = 14,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Realizar fondos con los codos cerca del cuerpo, flexionando los brazos.",
                            Nombre = "Fondos con codos estrechos"
                        },
                        new
                        {
                            IdEjercicio = 15,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Sentarse en un banco y levantar una mancuerna desde detrás de la cabeza hasta estirar el brazo.",
                            Nombre = "Extensión de Tríceps con Mancuerna Sentado y con los Brazos Elevados"
                        },
                        new
                        {
                            IdEjercicio = 16,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Realizar extensiones de tríceps con una barra V en una máquina de poleas, desde arriba hacia abajo.",
                            Nombre = "Empujes hacia Abajo con Barra V en Máquina de Poleas"
                        },
                        new
                        {
                            IdEjercicio = 17,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Acostarse en un banco y realizar fondos con los brazos extendidos detrás de la cabeza.",
                            Nombre = "Fondos en Banco"
                        },
                        new
                        {
                            IdEjercicio = 18,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Acostarse en un banco y levantar una barra desde detrás de la cabeza hasta estirar el brazo.",
                            Nombre = "Extensiones de Tríceps Acostado con Barra"
                        },
                        new
                        {
                            IdEjercicio = 19,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Realizar extensiones de tríceps con un cable cruzado, desde arriba hacia abajo.",
                            Nombre = "Empuje Hacia Abajo con Cable Cruzado"
                        },
                        new
                        {
                            IdEjercicio = 20,
                            AreaATrabajar = "Brazos",
                            Descripcion = "Realizar extensiones de tríceps con una cuerda de cable, desde arriba hacia abajo.",
                            Nombre = "Empuje hacia abajo con cuerda de cable"
                        },
                        new
                        {
                            IdEjercicio = 21,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Posición inicial: Ajuste la barra a la altura adecuada, pase debajo de la barra y sosténgala en la parte posterior de los hombros.",
                            Nombre = "Sentadilla con Barra"
                        },
                        new
                        {
                            IdEjercicio = 22,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Realizar una zancada hacia atrás con una pierna apoyada en un banco, flexionando ambas rodillas. Levantar el cuerpo de vuelta a la posición inicial.",
                            Nombre = "Sentadilla Búlgara con Mancuernas"
                        },
                        new
                        {
                            IdEjercicio = 23,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Dar un paso hacia adelante flexionando ambas rodillas hasta que formen ángulos de 90 grados. Volver a la posición inicial.",
                            Nombre = "Zancadas hacia adelante"
                        },
                        new
                        {
                            IdEjercicio = 24,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Realizar una zancada hacia atrás con una pierna, manteniendo la otra extendida y flexionando ambas rodillas. Volver a la posición inicial.",
                            Nombre = "Zancada de Reverencia con Barra"
                        },
                        new
                        {
                            IdEjercicio = 25,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Realizar una sentadilla con una barra olímpica, manteniendo la espalda recta y bajando hasta que los muslos estén paralelos al suelo. Volver a la posición inicial.",
                            Nombre = "Sentadilla con Barra Olímpica en Pivote"
                        },
                        new
                        {
                            IdEjercicio = 26,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Saltar con ambos pies sobre un cajón y aterrizar suavemente. Subir y bajar del cajón de forma controlada",
                            Nombre = "Salto al Cajón"
                        },
                        new
                        {
                            IdEjercicio = 27,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Sostener una pelota medicinal sobre la cabeza y realizar una sentadilla manteniendo la espalda recta. Volver a la posición inicial.",
                            Nombre = "Sentadilla con Pelota Medicinal en la Cabeza"
                        },
                        new
                        {
                            IdEjercicio = 28,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Ajustar la máquina a la altura adecuada, sostener la barra en la parte posterior de los hombros y realizar una sentadilla controlada.",
                            Nombre = "Sentadilla en Máquina Smith"
                        },
                        new
                        {
                            IdEjercicio = 29,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Realizar zancadas hacia atrás alternando las piernas, manteniendo la espalda recta y flexionando ambas rodillas. Volver a la posición inicial.",
                            Nombre = "Zancada de reverencia alternada con peso corporal"
                        },
                        new
                        {
                            IdEjercicio = 30,
                            AreaATrabajar = "Piernas",
                            Descripcion = "De pie en una máquina específica, levanta los talones tanto como puedas mientras exhalas, luego baja lentamente.",
                            Nombre = "Elevaciones de Pantorrilla en Máquina de Pie"
                        },
                        new
                        {
                            IdEjercicio = 31,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Sentado en una máquina, levanta los talones tanto como puedas mientras exhalas, luego baja lentamente.",
                            Nombre = "Elevaciones de Pantorrilla Sentado en Máquina"
                        },
                        new
                        {
                            IdEjercicio = 32,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Camina sobre las puntas de los pies, manteniendo los talones elevados del suelo. Puedes hacerlo en el lugar o desplazándote.",
                            Nombre = "Caminata de Puntas de Pie"
                        },
                        new
                        {
                            IdEjercicio = 33,
                            AreaATrabajar = "Piernas",
                            Descripcion = "De pie, levanta los talones tanto como puedas, manteniendo el equilibrio, y luego baja lentamente.",
                            Nombre = "Elevaciones de Pantorrilla"
                        },
                        new
                        {
                            IdEjercicio = 34,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Utilizando una barra sobre los hombros, levanta los talones tanto como puedas, manteniendo el equilibrio, y luego baja lentamente.",
                            Nombre = "Elevaciones de Pantorrilla con Barra"
                        },
                        new
                        {
                            IdEjercicio = 35,
                            AreaATrabajar = "Piernas",
                            Descripcion = "Con un cable, levanta los talones tanto como puedas, manteniendo el equilibrio, y luego baja lentamente.",
                            Nombre = "Elevación de Pantorrilla con Cable"
                        },
                        new
                        {
                            IdEjercicio = 36,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Acostarse en un banco plano, tomar la barra con un agarre ligeramente más ancho que los hombros, bajar la barra controladamente hasta el pecho y empujar hacia arriba para extender los brazos",
                            Nombre = "Press de Banca con Barra"
                        },
                        new
                        {
                            IdEjercicio = 37,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Apoyar las manos en una caja o banco, extender los brazos para levantar el cuerpo y luego flexionar los codos para bajar el cuerpo hasta que los brazos formen un ángulo de 90 grados",
                            Nombre = "Fondos en Caja"
                        },
                        new
                        {
                            IdEjercicio = 38,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Acostarse en un banco inclinado, sostener mancuernas con las palmas hacia adentro, abrir los brazos hasta que estén paralelos al suelo y volver a la posición inicial",
                            Nombre = "Aperturas de Pecho con Mancuernas en Banco Inclinado"
                        },
                        new
                        {
                            IdEjercicio = 39,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Acostarse en un banco inclinado, tomar la barra con un agarre ligeramente más ancho que los hombros, bajar la barra controladamente hasta el pecho y empujar hacia arriba para extender los brazos",
                            Nombre = "Press de Banca Inclinado con Barra"
                        },
                        new
                        {
                            IdEjercicio = 40,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Acostarse boca abajo en un banco, extender los brazos hacia adelante con las manos en el suelo y realizar un estiramiento de pecho",
                            Nombre = "Variación Cuatro de Estiramiento de Pecho"
                        },
                        new
                        {
                            IdEjercicio = 41,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Colocarse en posición de flexión con las manos y pies apoyados en el suelo, bajar el cuerpo flexionando los codos hasta que el pecho casi toque el suelo, y luego empujar para volver a la posición inicial",
                            Nombre = "Lagartija"
                        },
                        new
                        {
                            IdEjercicio = 42,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Realizar flexiones con el cuerpo inclinado a 45 grados, manteniendo la espalda recta y flexionando los codos para bajar el pecho hacia el suelo",
                            Nombre = "Flexión Inclinada"
                        },
                        new
                        {
                            IdEjercicio = 43,
                            AreaATrabajar = "Pecho",
                            Descripcion = "Realizar flexiones con el cuerpo inclinado hacia abajo a 90 grados, manteniendo la espalda recta y flexionando los codos para bajar el pecho hacia el suelo",
                            Nombre = "Flexión inclinado hacia abajo"
                        },
                        new
                        {
                            IdEjercicio = 44,
                            AreaATrabajar = "Pecho",
                            Descripcion = "De pie frente a una polea alta, tomar el agarre con ambas manos y abrir los brazos hacia los lados, manteniendo los codos ligeramente flexionados",
                            Nombre = "Apertura de Pecho con Polea"
                        },
                        new
                        {
                            IdEjercicio = 45,
                            AreaATrabajar = "Pecho",
                            Descripcion = "De pie entre dos poleas a la altura del pecho, empujar las manos hacia adelante extendiendo los brazos",
                            Nombre = "Press de Pecho con Cable"
                        },
                        new
                        {
                            IdEjercicio = 46,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "Acostado boca arriba, con las piernas extendidas, eleva las piernas hasta formar un ángulo recto con el cuerpo y luego baja lentamente",
                            Nombre = "Elevaciones de Pierna Acostado"
                        },
                        new
                        {
                            IdEjercicio = 47,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "En una máquina específica, acostado boca arriba, eleva el tronco flexionando el abdomen y luego baja lentamente.",
                            Nombre = "Despliegues con Máquina"
                        },
                        new
                        {
                            IdEjercicio = 48,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "\"Acostado boca abajo, con los brazos extendidos, eleva el tronco y las piernas, formando una \"\"V\"\" con el cuerpo.\"",
                            Nombre = "Variante Cuatro del Estiramiento Abdominal"
                        },
                        new
                        {
                            IdEjercicio = 49,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "En posición de plancha, apoyado en los antebrazos y pies, mantén la posición contraído el abdomen",
                            Nombre = "Plancha de Antebrazo"
                        },
                        new
                        {
                            IdEjercicio = 50,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "Colgado de una barra, eleva las rodillas hacia el pecho, manteniendo el abdomen contraído",
                            Nombre = "Elevaciones de Rodilla Colgando"
                        },
                        new
                        {
                            IdEjercicio = 51,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "Sentado con las piernas extendidas y una barra en el pecho, eleva el tronco flexionando el abdomen y luego baja lentamente.",
                            Nombre = "Despliegues con Barra"
                        },
                        new
                        {
                            IdEjercicio = 52,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "De pie frente a una polea baja, toma el agarre con ambas manos y realiza un crunch, flexionando el abdomen",
                            Nombre = "Crunch de Pie con Cable"
                        },
                        new
                        {
                            IdEjercicio = 53,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "Sentado con las rodillas flexionadas y una barra en el pecho, realiza un crunch flexionando el abdomen.",
                            Nombre = "Crunch de Rodillas con Barra en Polea"
                        },
                        new
                        {
                            IdEjercicio = 54,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "Acostado boca arriba con una mancuerna en el pecho, realiza un crunch flexionando el abdomen.",
                            Nombre = "Abdominales con Mancuerna"
                        },
                        new
                        {
                            IdEjercicio = 55,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "En posición de plancha, pasa una mancuerna de un lado a otro por debajo del pecho, manteniendo el abdomen contraído.",
                            Nombre = "Plancha con Pase de Mancuerna"
                        },
                        new
                        {
                            IdEjercicio = 56,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "En posición de plancha, alterna flexionar las rodillas hacia el pecho, manteniendo el abdomen contraído.",
                            Nombre = "Escalador de Montañas"
                        },
                        new
                        {
                            IdEjercicio = 57,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "Suspendido en un TRX, eleva las rodillas hacia el pecho, manteniendo el abdomen contraído.",
                            Nombre = "Rodillas al Pecho con TRX"
                        },
                        new
                        {
                            IdEjercicio = 58,
                            AreaATrabajar = "Abdomen",
                            Descripcion = "Acostado de lado con una mancuerna en el pecho, realiza un giro llevando la mancuerna hacia el suelo, manteniendo las piernas juntas.",
                            Nombre = "Giro Ruso con Mancuerna"
                        },
                        new
                        {
                            IdEjercicio = 59,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Realizar jacks verticales con una banda de resistencia sobre los tobillos, separando y juntando las piernas mientras mueves los brazos en dirección opuesta",
                            Nombre = "Bandas de Cardio para Martillo y Flexiones de Brazos Jacks"
                        },
                        new
                        {
                            IdEjercicio = 60,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Simular el movimiento de remo en un ergómetro, utilizando solo los brazos para impulsar el deslizador hacia atrás y luego volver a la posición inicial.",
                            Nombre = "Cardio Remo Ergo con Brazos Solamente"
                        },
                        new
                        {
                            IdEjercicio = 61,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Saltar y tocar los dedos de los pies con las manos, manteniendo las piernas extendidas.",
                            Nombre = "Toque de Dedo del Pie"
                        },
                        new
                        {
                            IdEjercicio = 62,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Dar pasos grandes hacia adelante alternando las piernas, manteniendo el torso erguido.",
                            Nombre = "Tijera Cardio hacia Delante"
                        },
                        new
                        {
                            IdEjercicio = 63,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Realizar movimientos de boxeo con los pies, dando pequeños saltos y pasos laterales rápidos.",
                            Nombre = "Cardio Box Pies Rápidos"
                        },
                        new
                        {
                            IdEjercicio = 64,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Saltar cruzando las piernas hacia adelante y hacia atrás, manteniendo el torso erguido.",
                            Nombre = "Cardio Cruces de Saltos"
                        },
                        new
                        {
                            IdEjercicio = 65,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Correr en una figura de ocho, cambiando de dirección rápidamente.",
                            Nombre = "Cardio Sprint en Figura de Ocho"
                        },
                        new
                        {
                            IdEjercicio = 66,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Saltar hacia adelante lo más lejos posible, aterrizando con las rodillas flexionadas.",
                            Nombre = "Salto Largo Cardio"
                        },
                        new
                        {
                            IdEjercicio = 67,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Correr a máxima velocidad durante un período corto de tiempo, seguido de un período de recuperación.",
                            Nombre = "Esprint de Carrera Cardiovascular"
                        },
                        new
                        {
                            IdEjercicio = 68,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Realizar movimientos de pedaleo en el aire, alternando las piernas rápidamente.",
                            Nombre = "Bicicleta de Asalto Cardiovascular"
                        },
                        new
                        {
                            IdEjercicio = 69,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Dar pasos grandes hacia adelante alternando las piernas, manteniendo el torso erguido.",
                            Nombre = "Tijera Cardio hacia Delante"
                        },
                        new
                        {
                            IdEjercicio = 70,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Saltar cruzando las piernas hacia adelante y hacia atrás, manteniendo el torso erguido.",
                            Nombre = "Cardio Cruces de Saltos"
                        },
                        new
                        {
                            IdEjercicio = 71,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Realizar jacks verticales, saltando y separando las piernas hacia los lados mientras mueves los brazos en dirección opuesta.",
                            Nombre = "Saltos de Jacks Cardio"
                        },
                        new
                        {
                            IdEjercicio = 72,
                            AreaATrabajar = "Cardio",
                            Descripcion = "Realizar caminatas diarias unos tres kilómetros como mínimo. ",
                            Nombre = "Caminar 3 kilometros"
                        },
                        new
                        {
                            IdEjercicio = 73,
                            AreaATrabajar = "Espalda",
                            Descripcion = "Agárrate a una barra horizontal con las manos más separadas que el ancho de los hombros. Levanta el cuerpo hasta que la barbilla supere la barra. Baja lentamente hasta la posición inicial.",
                            Nombre = "Dominadas"
                        },
                        new
                        {
                            IdEjercicio = 74,
                            AreaATrabajar = "Espalda",
                            Descripcion = "De pie, con los pies separados a la anchura de los hombros, sostenga una barra sobre la parte delantera de los muslos. Flexione las rodillas y la cadera hacia adelante, manteniendo la espalda recta. Tire de la barra hacia el pecho, manteniendo los codos cerca del cuerpo. Extienda los brazos para volver a la posición inicial.",
                            Nombre = "Remo con barra"
                        },
                        new
                        {
                            IdEjercicio = 75,
                            AreaATrabajar = "Espalda",
                            Descripcion = "Siéntese en la máquina de jalón al pecho y agarre la barra con las manos a la anchura de los hombros. Tire de la barra hacia el pecho, manteniendo la espalda recta y los codos cerca del cuerpo. Extienda los brazos para volver a la posición inicial.",
                            Nombre = "Jalón al pecho"
                        },
                        new
                        {
                            IdEjercicio = 76,
                            AreaATrabajar = "Espalda",
                            Descripcion = "Incline el torso hacia adelante desde la cintura, manteniendo la espalda recta. Sostenga una mancuerna en cada mano con las palmas hacia adentro. Tire de las mancuernas hacia la cadera, manteniendo los codos cerca del cuerpo. Baje las mancuernas lentamente a la posición inicial.",
                            Nombre = "Remo con mancuernas"
                        },
                        new
                        {
                            IdEjercicio = 77,
                            AreaATrabajar = "Espalda",
                            Descripcion = "Siéntese en una máquina de poleas con un accesorio de agarre frontal. Agarre las manijas con las palmas una frente a la otra. Tire de las manijas hacia la cara, manteniendo los codos cerca del cuerpo. Extienda los brazos para volver a la posición inicial.",
                            Nombre = "Face pulls"
                        });
                });

            modelBuilder.Entity("SayaGym.Models.EjercicioRutina", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<int>("DiaEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioIdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("RutinaIdRutina")
                        .HasColumnType("int");

                    b.HasKey("IdEjercicio", "IdRutina", "DiaEjercicio");

                    b.HasIndex("EjercicioIdEjercicio");

                    b.HasIndex("RutinaIdRutina");

                    b.ToTable("EjerciciosRutina");
                });

            modelBuilder.Entity("SayaGym.Models.Enfermedad", b =>
                {
                    b.Property<int>("IdEnfermedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnfermedad"));

                    b.Property<string>("NombreEnfermedad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEnfermedad");

                    b.ToTable("Enfermedades");

                    b.HasData(
                        new
                        {
                            IdEnfermedad = 1,
                            NombreEnfermedad = "Hipertensión"
                        },
                        new
                        {
                            IdEnfermedad = 2,
                            NombreEnfermedad = "Diabetes"
                        },
                        new
                        {
                            IdEnfermedad = 3,
                            NombreEnfermedad = "Problemas de espalda"
                        },
                        new
                        {
                            IdEnfermedad = 4,
                            NombreEnfermedad = "Problemas de rodilla"
                        },
                        new
                        {
                            IdEnfermedad = 5,
                            NombreEnfermedad = "Asma"
                        },
                        new
                        {
                            IdEnfermedad = 6,
                            NombreEnfermedad = "Enfermedad cardíaca"
                        },
                        new
                        {
                            IdEnfermedad = 7,
                            NombreEnfermedad = "Artritis"
                        },
                        new
                        {
                            IdEnfermedad = 8,
                            NombreEnfermedad = "Osteoporosis"
                        });
                });

            modelBuilder.Entity("SayaGym.Models.EnfermedadProhibidaEjercicio", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdEnfermedad")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioIdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("EnfermedadIdEnfermedad")
                        .HasColumnType("int");

                    b.HasKey("IdEjercicio", "IdEnfermedad");

                    b.HasIndex("EjercicioIdEjercicio");

                    b.HasIndex("EnfermedadIdEnfermedad");

                    b.ToTable("EnfermedadesProhibidasEjercicios");

                    b.HasData(
                        new
                        {
                            IdEjercicio = 4,
                            IdEnfermedad = 7,
                            EjercicioIdEjercicio = 4,
                            EnfermedadIdEnfermedad = 7
                        },
                        new
                        {
                            IdEjercicio = 8,
                            IdEnfermedad = 7,
                            EjercicioIdEjercicio = 8,
                            EnfermedadIdEnfermedad = 7
                        },
                        new
                        {
                            IdEjercicio = 10,
                            IdEnfermedad = 7,
                            EjercicioIdEjercicio = 10,
                            EnfermedadIdEnfermedad = 7
                        },
                        new
                        {
                            IdEjercicio = 12,
                            IdEnfermedad = 7,
                            EjercicioIdEjercicio = 12,
                            EnfermedadIdEnfermedad = 7
                        },
                        new
                        {
                            IdEjercicio = 17,
                            IdEnfermedad = 7,
                            EjercicioIdEjercicio = 17,
                            EnfermedadIdEnfermedad = 7
                        },
                        new
                        {
                            IdEjercicio = 17,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 17,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 18,
                            IdEnfermedad = 7,
                            EjercicioIdEjercicio = 18,
                            EnfermedadIdEnfermedad = 7
                        },
                        new
                        {
                            IdEjercicio = 21,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 21,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 21,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 21,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 21,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 21,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 22,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 22,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 22,
                            IdEnfermedad = 2,
                            EjercicioIdEjercicio = 22,
                            EnfermedadIdEnfermedad = 2
                        },
                        new
                        {
                            IdEjercicio = 22,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 22,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 23,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 23,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 24,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 24,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 25,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 25,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 26,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 26,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 26,
                            IdEnfermedad = 5,
                            EjercicioIdEjercicio = 26,
                            EnfermedadIdEnfermedad = 5
                        },
                        new
                        {
                            IdEjercicio = 27,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 27,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 28,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 28,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 29,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 29,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 39,
                            IdEnfermedad = 5,
                            EjercicioIdEjercicio = 39,
                            EnfermedadIdEnfermedad = 5
                        },
                        new
                        {
                            IdEjercicio = 41,
                            IdEnfermedad = 2,
                            EjercicioIdEjercicio = 41,
                            EnfermedadIdEnfermedad = 2
                        },
                        new
                        {
                            IdEjercicio = 41,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 41,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 41,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 41,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 41,
                            IdEnfermedad = 6,
                            EjercicioIdEjercicio = 41,
                            EnfermedadIdEnfermedad = 6
                        },
                        new
                        {
                            IdEjercicio = 46,
                            IdEnfermedad = 6,
                            EjercicioIdEjercicio = 46,
                            EnfermedadIdEnfermedad = 6
                        },
                        new
                        {
                            IdEjercicio = 49,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 49,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 49,
                            IdEnfermedad = 2,
                            EjercicioIdEjercicio = 49,
                            EnfermedadIdEnfermedad = 2
                        },
                        new
                        {
                            IdEjercicio = 49,
                            IdEnfermedad = 5,
                            EjercicioIdEjercicio = 49,
                            EnfermedadIdEnfermedad = 5
                        },
                        new
                        {
                            IdEjercicio = 50,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 50,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 50,
                            IdEnfermedad = 2,
                            EjercicioIdEjercicio = 50,
                            EnfermedadIdEnfermedad = 2
                        },
                        new
                        {
                            IdEjercicio = 50,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 50,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 50,
                            IdEnfermedad = 6,
                            EjercicioIdEjercicio = 50,
                            EnfermedadIdEnfermedad = 6
                        },
                        new
                        {
                            IdEjercicio = 54,
                            IdEnfermedad = 8,
                            EjercicioIdEjercicio = 54,
                            EnfermedadIdEnfermedad = 8
                        },
                        new
                        {
                            IdEjercicio = 54,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 54,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 55,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 55,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 55,
                            IdEnfermedad = 2,
                            EjercicioIdEjercicio = 55,
                            EnfermedadIdEnfermedad = 2
                        },
                        new
                        {
                            IdEjercicio = 55,
                            IdEnfermedad = 5,
                            EjercicioIdEjercicio = 55,
                            EnfermedadIdEnfermedad = 5
                        },
                        new
                        {
                            IdEjercicio = 56,
                            IdEnfermedad = 5,
                            EjercicioIdEjercicio = 56,
                            EnfermedadIdEnfermedad = 5
                        },
                        new
                        {
                            IdEjercicio = 56,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 56,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 56,
                            IdEnfermedad = 2,
                            EjercicioIdEjercicio = 56,
                            EnfermedadIdEnfermedad = 2
                        },
                        new
                        {
                            IdEjercicio = 57,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 57,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 58,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 58,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 59,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 59,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 60,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 60,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 63,
                            IdEnfermedad = 5,
                            EjercicioIdEjercicio = 63,
                            EnfermedadIdEnfermedad = 5
                        },
                        new
                        {
                            IdEjercicio = 63,
                            IdEnfermedad = 1,
                            EjercicioIdEjercicio = 63,
                            EnfermedadIdEnfermedad = 1
                        },
                        new
                        {
                            IdEjercicio = 64,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 64,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 65,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 65,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 66,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 66,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 67,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 67,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 67,
                            IdEnfermedad = 5,
                            EjercicioIdEjercicio = 67,
                            EnfermedadIdEnfermedad = 5
                        },
                        new
                        {
                            IdEjercicio = 70,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 70,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 71,
                            IdEnfermedad = 4,
                            EjercicioIdEjercicio = 71,
                            EnfermedadIdEnfermedad = 4
                        },
                        new
                        {
                            IdEjercicio = 73,
                            IdEnfermedad = 3,
                            EjercicioIdEjercicio = 73,
                            EnfermedadIdEnfermedad = 3
                        },
                        new
                        {
                            IdEjercicio = 73,
                            IdEnfermedad = 8,
                            EjercicioIdEjercicio = 73,
                            EnfermedadIdEnfermedad = 8
                        });
                });

            modelBuilder.Entity("SayaGym.Models.EnfermedadUsuario", b =>
                {
                    b.Property<int>("IdEnfermedad")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("EnfermedadIdEnfermedad")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdEnfermedad", "IdUsuario");

                    b.HasIndex("EnfermedadIdEnfermedad");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("EnfermedadesUsuario");
                });

            modelBuilder.Entity("SayaGym.Models.Rutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutina"));

                    b.Property<DateTime>("FechaRutina")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdRutina");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Rutina");
                });

            modelBuilder.Entity("SayaGym.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Estatura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Objetivo")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Cedula = "11111111",
                            Contraseña = "admin",
                            Correo = "admin@gmail.com",
                            Dirección = "",
                            Estado = "A",
                            Estatura = 170m,
                            FechaDeNacimiento = new DateTime(2024, 5, 29, 19, 7, 9, 378, DateTimeKind.Local).AddTicks(9840),
                            Nombre = "Admin",
                            Objetivo = 0,
                            Peso = 80m,
                            Rol = 0,
                            Sexo = "M",
                            Teléfono = "00000000"
                        });
                });

            modelBuilder.Entity("SayaGym.Models.AreasATrabajarUsuario", b =>
                {
                    b.HasOne("SayaGym.Models.Usuario", "Usuario")
                        .WithMany("AreasATrabajar")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SayaGym.Models.EjercicioRutina", b =>
                {
                    b.HasOne("SayaGym.Models.Ejercicio", "Ejercicio")
                        .WithMany("Ejercicios")
                        .HasForeignKey("EjercicioIdEjercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SayaGym.Models.Rutina", "Rutina")
                        .WithMany("EjerciciosRutina")
                        .HasForeignKey("RutinaIdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("SayaGym.Models.EnfermedadProhibidaEjercicio", b =>
                {
                    b.HasOne("SayaGym.Models.Ejercicio", "Ejercicio")
                        .WithMany("EnfermedadesProhibidasUsuario")
                        .HasForeignKey("EjercicioIdEjercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SayaGym.Models.Enfermedad", "Enfermedad")
                        .WithMany("EnfermedadesProhibidasEjercicios")
                        .HasForeignKey("EnfermedadIdEnfermedad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Enfermedad");
                });

            modelBuilder.Entity("SayaGym.Models.EnfermedadUsuario", b =>
                {
                    b.HasOne("SayaGym.Models.Enfermedad", "Enfermedad")
                        .WithMany("EnfermedadesUsuarios")
                        .HasForeignKey("EnfermedadIdEnfermedad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SayaGym.Models.Usuario", "Usuario")
                        .WithMany("EnfermedadesUsuario")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermedad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SayaGym.Models.Rutina", b =>
                {
                    b.HasOne("SayaGym.Models.Usuario", "Usuario")
                        .WithOne("Rutina")
                        .HasForeignKey("SayaGym.Models.Rutina", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SayaGym.Models.Ejercicio", b =>
                {
                    b.Navigation("Ejercicios");

                    b.Navigation("EnfermedadesProhibidasUsuario");
                });

            modelBuilder.Entity("SayaGym.Models.Enfermedad", b =>
                {
                    b.Navigation("EnfermedadesProhibidasEjercicios");

                    b.Navigation("EnfermedadesUsuarios");
                });

            modelBuilder.Entity("SayaGym.Models.Rutina", b =>
                {
                    b.Navigation("EjerciciosRutina");
                });

            modelBuilder.Entity("SayaGym.Models.Usuario", b =>
                {
                    b.Navigation("AreasATrabajar");

                    b.Navigation("EnfermedadesUsuario");

                    b.Navigation("Rutina")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
